//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioVet.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudioVet.Core.Properties.translation", typeof(translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string bool_No {
            get {
                return ResourceManager.GetString("bool_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string bool_Yes {
            get {
                return ResourceManager.GetString("bool_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire from scanner.
        /// </summary>
        internal static string btn_acquire {
            get {
                return ResourceManager.GetString("btn_acquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btn_AddAnimal {
            get {
                return ResourceManager.GetString("btn_AddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        internal static string btn_addFile {
            get {
                return ResourceManager.GetString("btn_addFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        internal static string btn_apply_changes {
            get {
                return ResourceManager.GetString("btn_apply_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Capture folder.
        /// </summary>
        internal static string btn_captureFolder {
            get {
                return ResourceManager.GetString("btn_captureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        internal static string btn_createInvoice {
            get {
                return ResourceManager.GetString("btn_createInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btn_DelAnimal {
            get {
                return ResourceManager.GetString("btn_DelAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btn_EditAnimal {
            get {
                return ResourceManager.GetString("btn_EditAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string btn_explore {
            get {
                return ResourceManager.GetString("btn_explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore path.
        /// </summary>
        internal static string btn_explorePath {
            get {
                return ResourceManager.GetString("btn_explorePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate files.
        /// </summary>
        internal static string btn_navigateFiles {
            get {
                return ResourceManager.GetString("btn_navigateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Visits.
        /// </summary>
        internal static string btn_OpenVisits {
            get {
                return ResourceManager.GetString("btn_OpenVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page setup.
        /// </summary>
        internal static string btn_pageSetup {
            get {
                return ResourceManager.GetString("btn_pageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string btn_print {
            get {
                return ResourceManager.GetString("btn_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print invoice.
        /// </summary>
        internal static string btn_printInvoice {
            get {
                return ResourceManager.GetString("btn_printInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print report.
        /// </summary>
        internal static string btn_printReport {
            get {
                return ResourceManager.GetString("btn_printReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string btn_shellexec {
            get {
                return ResourceManager.GetString("btn_shellexec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Changes.
        /// </summary>
        internal static string btn_undo_changes {
            get {
                return ResourceManager.GetString("btn_undo_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimalID.
        /// </summary>
        internal static string dbcol_animal_animalid {
            get {
                return ResourceManager.GetString("dbcol_animal_animalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        internal static string dbcol_animal_identification {
            get {
                return ResourceManager.GetString("dbcol_animal_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string dbcol_animal_label {
            get {
                return ResourceManager.GetString("dbcol_animal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string dbcol_animal_race {
            get {
                return ResourceManager.GetString("dbcol_animal_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string dbcol_animal_species {
            get {
                return ResourceManager.GetString("dbcol_animal_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string dbcol_dispense_charge {
            get {
                return ResourceManager.GetString("dbcol_dispense_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DispenseID.
        /// </summary>
        internal static string dbcol_dispense_dispenseid {
            get {
                return ResourceManager.GetString("dbcol_dispense_dispenseid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_dispense_notes {
            get {
                return ResourceManager.GetString("dbcol_dispense_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PharmaceuticalID.
        /// </summary>
        internal static string dbcol_dispense_pharmaceuticalid {
            get {
                return ResourceManager.GetString("dbcol_dispense_pharmaceuticalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string dbcol_dispense_quantity {
            get {
                return ResourceManager.GetString("dbcol_dispense_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qt..
        /// </summary>
        internal static string dbcol_dispense_quantity_abb {
            get {
                return ResourceManager.GetString("dbcol_dispense_quantity_abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitID.
        /// </summary>
        internal static string dbcol_dispense_visitid {
            get {
                return ResourceManager.GetString("dbcol_dispense_visitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dbcol_document_description {
            get {
                return ResourceManager.GetString("dbcol_document_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentID.
        /// </summary>
        internal static string dbcol_document_documentid {
            get {
                return ResourceManager.GetString("dbcol_document_documentid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string dbcol_document_filename {
            get {
                return ResourceManager.GetString("dbcol_document_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_document_notes {
            get {
                return ResourceManager.GetString("dbcol_document_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintFlag.
        /// </summary>
        internal static string dbcol_document_printflag {
            get {
                return ResourceManager.GetString("dbcol_document_printflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitID.
        /// </summary>
        internal static string dbcol_document_visitid {
            get {
                return ResourceManager.GetString("dbcol_document_visitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimalID.
        /// </summary>
        internal static string dbcol_patient_animalid {
            get {
                return ResourceManager.GetString("dbcol_patient_animalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        internal static string dbcol_patient_birthdate {
            get {
                return ResourceManager.GetString("dbcol_patient_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string dbcol_patient_firstname {
            get {
                return ResourceManager.GetString("dbcol_patient_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        internal static string dbcol_patient_identification {
            get {
                return ResourceManager.GetString("dbcol_patient_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_patient_notes {
            get {
                return ResourceManager.GetString("dbcol_patient_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientID.
        /// </summary>
        internal static string dbcol_patient_patientid {
            get {
                return ResourceManager.GetString("dbcol_patient_patientid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonID.
        /// </summary>
        internal static string dbcol_patient_personid {
            get {
                return ResourceManager.GetString("dbcol_patient_personid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine1.
        /// </summary>
        internal static string dbcol_person_addressline1 {
            get {
                return ResourceManager.GetString("dbcol_person_addressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine2.
        /// </summary>
        internal static string dbcol_person_addressline2 {
            get {
                return ResourceManager.GetString("dbcol_person_addressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        internal static string dbcol_person_birthcity {
            get {
                return ResourceManager.GetString("dbcol_person_birthcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string dbcol_person_birthdate {
            get {
                return ResourceManager.GetString("dbcol_person_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string dbcol_person_city {
            get {
                return ResourceManager.GetString("dbcol_person_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string dbcol_person_country {
            get {
                return ResourceManager.GetString("dbcol_person_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        internal static string dbcol_person_email {
            get {
                return ResourceManager.GetString("dbcol_person_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string dbcol_person_fax {
            get {
                return ResourceManager.GetString("dbcol_person_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string dbcol_person_firstname {
            get {
                return ResourceManager.GetString("dbcol_person_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string dbcol_person_lastname {
            get {
                return ResourceManager.GetString("dbcol_person_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_person_notes {
            get {
                return ResourceManager.GetString("dbcol_person_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonID.
        /// </summary>
        internal static string dbcol_person_personid {
            get {
                return ResourceManager.GetString("dbcol_person_personid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        internal static string dbcol_person_phone1 {
            get {
                return ResourceManager.GetString("dbcol_person_phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        internal static string dbcol_person_phone2 {
            get {
                return ResourceManager.GetString("dbcol_person_phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string dbcol_person_province {
            get {
                return ResourceManager.GetString("dbcol_person_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxCode.
        /// </summary>
        internal static string dbcol_person_taxcode {
            get {
                return ResourceManager.GetString("dbcol_person_taxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VatNumber.
        /// </summary>
        internal static string dbcol_person_vatnumber {
            get {
                return ResourceManager.GetString("dbcol_person_vatnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        internal static string dbcol_person_zipcode {
            get {
                return ResourceManager.GetString("dbcol_person_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster.
        /// </summary>
        internal static string dbcol_pharmaceutical_booster {
            get {
                return ResourceManager.GetString("dbcol_pharmaceutical_booster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dbcol_pharmaceutical_description {
            get {
                return ResourceManager.GetString("dbcol_pharmaceutical_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccine.
        /// </summary>
        internal static string dbcol_pharmaceutical_isvaccine {
            get {
                return ResourceManager.GetString("dbcol_pharmaceutical_isvaccine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string dbcol_pharmaceutical_label {
            get {
                return ResourceManager.GetString("dbcol_pharmaceutical_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PharmaceuticalID.
        /// </summary>
        internal static string dbcol_pharmaceutical_pharmaceuticalid {
            get {
                return ResourceManager.GetString("dbcol_pharmaceutical_pharmaceuticalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string dbcol_pharmaceutical_rate {
            get {
                return ResourceManager.GetString("dbcol_pharmaceutical_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string dbcol_reminder_completed {
            get {
                return ResourceManager.GetString("dbcol_reminder_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dbcol_reminder_description {
            get {
                return ResourceManager.GetString("dbcol_reminder_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate.
        /// </summary>
        internal static string dbcol_reminder_duedate {
            get {
                return ResourceManager.GetString("dbcol_reminder_duedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_reminder_notes {
            get {
                return ResourceManager.GetString("dbcol_reminder_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReminderID.
        /// </summary>
        internal static string dbcol_reminder_reminderid {
            get {
                return ResourceManager.GetString("dbcol_reminder_reminderid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitID.
        /// </summary>
        internal static string dbcol_reminder_visitid {
            get {
                return ResourceManager.GetString("dbcol_reminder_visitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string dbcol_reminder_warning {
            get {
                return ResourceManager.GetString("dbcol_reminder_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string dbcol_service_charge {
            get {
                return ResourceManager.GetString("dbcol_service_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_service_notes {
            get {
                return ResourceManager.GetString("dbcol_service_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceID.
        /// </summary>
        internal static string dbcol_service_serviceid {
            get {
                return ResourceManager.GetString("dbcol_service_serviceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTypeID.
        /// </summary>
        internal static string dbcol_service_servicetypeid {
            get {
                return ResourceManager.GetString("dbcol_service_servicetypeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitID.
        /// </summary>
        internal static string dbcol_service_visitid {
            get {
                return ResourceManager.GetString("dbcol_service_visitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dbcol_servicetype_description {
            get {
                return ResourceManager.GetString("dbcol_servicetype_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string dbcol_servicetype_label {
            get {
                return ResourceManager.GetString("dbcol_servicetype_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string dbcol_servicetype_rate {
            get {
                return ResourceManager.GetString("dbcol_servicetype_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTypeID.
        /// </summary>
        internal static string dbcol_servicetype_servicetypeid {
            get {
                return ResourceManager.GetString("dbcol_servicetype_servicetypeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dbcol_visit_description {
            get {
                return ResourceManager.GetString("dbcol_visit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string dbcol_visit_doctor {
            get {
                return ResourceManager.GetString("dbcol_visit_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string dbcol_visit_notes {
            get {
                return ResourceManager.GetString("dbcol_visit_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientID.
        /// </summary>
        internal static string dbcol_visit_patientid {
            get {
                return ResourceManager.GetString("dbcol_visit_patientid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string dbcol_visit_report {
            get {
                return ResourceManager.GetString("dbcol_visit_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitDate.
        /// </summary>
        internal static string dbcol_visit_visitdate {
            get {
                return ResourceManager.GetString("dbcol_visit_visitdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitID.
        /// </summary>
        internal static string dbcol_visit_visitid {
            get {
                return ResourceManager.GetString("dbcol_visit_visitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitTypeID.
        /// </summary>
        internal static string dbcol_visit_visittypeid {
            get {
                return ResourceManager.GetString("dbcol_visit_visittypeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dbcol_visittype_description {
            get {
                return ResourceManager.GetString("dbcol_visittype_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string dbcol_visittype_label {
            get {
                return ResourceManager.GetString("dbcol_visittype_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitTypeID.
        /// </summary>
        internal static string dbcol_visittype_visittypeid {
            get {
                return ResourceManager.GetString("dbcol_visittype_visittypeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        internal static string dbcol_zipcode_address1 {
            get {
                return ResourceManager.GetString("dbcol_zipcode_address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string dbcol_zipcode_address2 {
            get {
                return ResourceManager.GetString("dbcol_zipcode_address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City1.
        /// </summary>
        internal static string dbcol_zipcode_city1 {
            get {
                return ResourceManager.GetString("dbcol_zipcode_city1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City2.
        /// </summary>
        internal static string dbcol_zipcode_city2 {
            get {
                return ResourceManager.GetString("dbcol_zipcode_city2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string dbcol_zipcode_country {
            get {
                return ResourceManager.GetString("dbcol_zipcode_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUG.
        /// </summary>
        internal static string dbcol_zipcode_dug {
            get {
                return ResourceManager.GetString("dbcol_zipcode_dug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction1.
        /// </summary>
        internal static string dbcol_zipcode_fraction1 {
            get {
                return ResourceManager.GetString("dbcol_zipcode_fraction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction2.
        /// </summary>
        internal static string dbcol_zipcode_fraction2 {
            get {
                return ResourceManager.GetString("dbcol_zipcode_fraction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string dbcol_zipcode_number {
            get {
                return ResourceManager.GetString("dbcol_zipcode_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string dbcol_zipcode_province {
            get {
                return ResourceManager.GetString("dbcol_zipcode_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string dbcol_zipcode_zipcode {
            get {
                return ResourceManager.GetString("dbcol_zipcode_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string dlg_error {
            get {
                return ResourceManager.GetString("dlg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes Before Exit ?.
        /// </summary>
        internal static string dlg_save_changes {
            get {
                return ResourceManager.GetString("dlg_save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ppsearch_address {
            get {
                return ResourceManager.GetString("ppsearch_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string ppsearch_alabel {
            get {
                return ResourceManager.GetString("ppsearch_alabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string ppsearch_arace {
            get {
                return ResourceManager.GetString("ppsearch_arace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string ppsearch_aspecies {
            get {
                return ResourceManager.GetString("ppsearch_aspecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string ppsearch_pfirstname {
            get {
                return ResourceManager.GetString("ppsearch_pfirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string ppsearch_plastname {
            get {
                return ResourceManager.GetString("ppsearch_plastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed with StudioVet.
        /// </summary>
        internal static string print_footer {
            get {
                return ResourceManager.GetString("print_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition from WIA device failed.
        /// </summary>
        internal static string str_acquisitionFailed {
            get {
                return ResourceManager.GetString("str_acquisitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string str_address {
            get {
                return ResourceManager.GetString("str_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal.
        /// </summary>
        internal static string str_animal {
            get {
                return ResourceManager.GetString("str_animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Directory.
        /// </summary>
        internal static string str_Animal_Directory {
            get {
                return ResourceManager.GetString("str_Animal_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animali.
        /// </summary>
        internal static string str_Animals {
            get {
                return ResourceManager.GetString("str_Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boosters.
        /// </summary>
        internal static string str_Boosters {
            get {
                return ResourceManager.GetString("str_Boosters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string str_code {
            get {
                return ResourceManager.GetString("str_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Form.
        /// </summary>
        internal static string str_Customer_Form {
            get {
                return ResourceManager.GetString("str_Customer_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string str_date {
            get {
                return ResourceManager.GetString("str_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete last invoice.
        /// </summary>
        internal static string str_delLastInvoice {
            get {
                return ResourceManager.GetString("str_delLastInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string str_description {
            get {
                return ResourceManager.GetString("str_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispenses.
        /// </summary>
        internal static string str_dispenses {
            get {
                return ResourceManager.GetString("str_dispenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string str_doctor {
            get {
                return ResourceManager.GetString("str_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string str_documents {
            get {
                return ResourceManager.GetString("str_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string str_Edit {
            get {
                return ResourceManager.GetString("str_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string str_Failed {
            get {
                return ResourceManager.GetString("str_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string str_html {
            get {
                return ResourceManager.GetString("str_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string str_invoice {
            get {
                return ResourceManager.GetString("str_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string str_invoiceColCode {
            get {
                return ResourceManager.GetString("str_invoiceColCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string str_invoiceColDescription {
            get {
                return ResourceManager.GetString("str_invoiceColDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTITY.
        /// </summary>
        internal static string str_invoiceColQuantity {
            get {
                return ResourceManager.GetString("str_invoiceColQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT PRICE.
        /// </summary>
        internal static string str_invoiceColUnitPrice {
            get {
                return ResourceManager.GetString("str_invoiceColUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string str_invoiceCurrency {
            get {
                return ResourceManager.GetString("str_invoiceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string str_invoiceCustomerDataTitle {
            get {
                return ResourceManager.GetString("str_invoiceCustomerDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string str_invoiceDataTitle {
            get {
                return ResourceManager.GetString("str_invoiceDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date.
        /// </summary>
        internal static string str_invoiceDate {
            get {
                return ResourceManager.GetString("str_invoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand total.
        /// </summary>
        internal static string str_invoiceGrandTotal {
            get {
                return ResourceManager.GetString("str_invoiceGrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        internal static string str_invoiceNum {
            get {
                return ResourceManager.GetString("str_invoiceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string str_invoicePaymentOther {
            get {
                return ResourceManager.GetString("str_invoicePaymentOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment terms.
        /// </summary>
        internal static string str_invoicePaymentTerms {
            get {
                return ResourceManager.GetString("str_invoicePaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string str_invoiceTax {
            get {
                return ResourceManager.GetString("str_invoiceTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        internal static string str_invoiceTaxCodeAbb {
            get {
                return ResourceManager.GetString("str_invoiceTaxCodeAbb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Income.
        /// </summary>
        internal static string str_invoiceTaxIncome {
            get {
                return ResourceManager.GetString("str_invoiceTaxIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services and dispenses.
        /// </summary>
        internal static string str_invoiceTitle {
            get {
                return ResourceManager.GetString("str_invoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string str_invoiceTotal {
            get {
                return ResourceManager.GetString("str_invoiceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string str_invoiceVat {
            get {
                return ResourceManager.GetString("str_invoiceVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VN.
        /// </summary>
        internal static string str_invoiceVatAbb {
            get {
                return ResourceManager.GetString("str_invoiceVatAbb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string str_Month {
            get {
                return ResourceManager.GetString("str_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First &amp; last names.
        /// </summary>
        internal static string str_nameAndSurname {
            get {
                return ResourceManager.GetString("str_nameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will take effect after rebooting the application.
        /// </summary>
        internal static string str_needRestart {
            get {
                return ResourceManager.GetString("str_needRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Visit.
        /// </summary>
        internal static string str_NewVisit {
            get {
                return ResourceManager.GetString("str_NewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string str_notes {
            get {
                return ResourceManager.GetString("str_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string str_Ok {
            get {
                return ResourceManager.GetString("str_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text is empty. Please retry..
        /// </summary>
        internal static string str_oopsTextIsEmpty {
            get {
                return ResourceManager.GetString("str_oopsTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string str_owner {
            get {
                return ResourceManager.GetString("str_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string str_Patient {
            get {
                return ResourceManager.GetString("str_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Form.
        /// </summary>
        internal static string str_Patient_Form {
            get {
                return ResourceManager.GetString("str_Patient_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string str_period {
            get {
                return ResourceManager.GetString("str_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical Directory.
        /// </summary>
        internal static string str_Pharmaceutical_Directory {
            get {
                return ResourceManager.GetString("str_Pharmaceutical_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string str_ReadOnly {
            get {
                return ResourceManager.GetString("str_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string str_refresh {
            get {
                return ResourceManager.GetString("str_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left.
        /// </summary>
        internal static string str_reminderCdown {
            get {
                return ResourceManager.GetString("str_reminderCdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string str_report {
            get {
                return ResourceManager.GetString("str_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Directory.
        /// </summary>
        internal static string str_Service_Directory {
            get {
                return ResourceManager.GetString("str_Service_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string str_services {
            get {
                return ResourceManager.GetString("str_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the last created invoice ?.
        /// </summary>
        internal static string str_sureToDelInvoice {
            get {
                return ResourceManager.GetString("str_sureToDelInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccinations.
        /// </summary>
        internal static string str_vaccinations {
            get {
                return ResourceManager.GetString("str_vaccinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT value not valid. Insert a valid percent and check the character used as decimal separartor.
        /// </summary>
        internal static string str_vatParseError {
            get {
                return ResourceManager.GetString("str_vatParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Directory.
        /// </summary>
        internal static string str_Visit_Directory {
            get {
                return ResourceManager.GetString("str_Visit_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string str_visits {
            get {
                return ResourceManager.GetString("str_visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit type.
        /// </summary>
        internal static string str_visitType {
            get {
                return ResourceManager.GetString("str_visitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string str_Year {
            get {
                return ResourceManager.GetString("str_Year", resourceCulture);
            }
        }
    }
}
